### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by m4rc1e** [alexeiva/yanone-kaffesatz#3]
Local vs Google fonts api

![screen shot 2016-11-14 at 13 54 56](https://cloud.githubusercontent.com/assets/7525512/20265802/5e1d07f4-aa73-11e6-9bf6-76877b619f7a.png)

I'll start writing a glyphsapp test/fix script so it can do all of this automatically :-)

**Comment by alexeiva** [comment]
need to regress to legacy version.

**Comment by alexeiva** [comment]
Fixed. @m4rc1e this script is a real CF-terminator! Thank you

<img width="1328" alt="screen shot 2016-11-21 at 12 02 27 pm" src="https://cloud.githubusercontent.com/assets/16634089/20480380/84bd548a-afe2-11e6-97c8-79a3adeefa83.png">
